bitacora/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from bitacora import views
from bitacora.views import *
import bitacora.views as views
from django.contrib.auth.decorators import login_required


urlpatterns = patterns('',
    url(r'^bitacora$', login_required(views.Bitacora.as_view()), name='bitacora'),
)

registro/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from registro import views
from registro.views import *
import registro.views as views
from django.contrib.auth.decorators import login_required


urlpatterns = patterns('',
    url(r'^index$', login_required(Index.as_view()), name='index'),
    ##### Crud de los reportes ######
    url(r'^consultar_reporte$', login_required(views.Consultar_reporte.as_view()), name='consultar_reporte'),
    url(r'^registrar_reporte$', login_required(views.Registrar_reporte.as_view()), name='registrar_reporte'),
    url(r'^editar_reporte/(?P<pk>\d+)$', login_required(views.Editar_reporte.as_view()), name='editar_reporte'),
    url(r'^borrar_reporte/(?P<pk>\d+)$', login_required(views.Borrar_reporte.as_view()), name='borrar_reporte'),
    url(r'^detallar_reporte/(?P<pk>\d+)$', login_required(views.Detallar_reporte.as_view()), name='detallar_reporte'),
    ##### Filtros de búsqueda #####
    url(r'^buscar/$', login_required(views.Buscar_reporte.as_view()), name='buscar'),
    url(r'^busqueda/$', busqueda, name='busqueda'),
)

reporte_mensual_proyecto/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^', include('usuarios.urls', namespace='usuarios')),
    url(r'^', include('registro.urls', namespace='registro')),
    url(r'^', include('bitacora.urls', namespace='bitacora')),
    url(r'^admin/', include(admin.site.urls)),
]

registro/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.core.urlresolvers import reverse
from datetime import datetime


class Reporte(models.Model):
    """
    Modelo de un Reporte de actividades de un proyecto.
    """
    autor = models.CharField(max_length=400, blank=True,null=True)
    nombre_proyecto = models.CharField(max_length=400, blank=True,null=True)
    nombre_caravisible = models.CharField(max_length=4000, blank=True,null=True)
    nombre_director = models.CharField(max_length=400, blank=True,null=True)
    mes = models.CharField(max_length=400, blank=True,null=True)
    ano = models.CharField(max_length=400, blank=True,null=True)
    desc_avance = models.CharField(max_length=5000, blank=True,null=True)
    obstaculos = models.CharField(max_length=5000, blank=True,null=True)
    nombre_trab_1 = models.CharField(max_length=400, blank=True,null=True)
    cargo_trab_1 = models.CharField(max_length=400, blank=True,null=True)
    act_rea_trab_1 = models.CharField(max_length=5000, blank=True,null=True)
    enlaces_trab_1 = models.CharField(max_length=5000, blank=True,null=True)
    nombre_trab_2 = models.CharField(max_length=400, blank=True,null=True)
    cargo_trab_2 = models.CharField(max_length=400, blank=True,null=True)
    act_rea_trab_2 = models.CharField(max_length=5000, blank=True,null=True)
    enlaces_trab_2 = models.CharField(max_length=5000, blank=True,null=True)
    nombre_trab_3 = models.CharField(max_length=400, blank=True,null=True)
    cargo_trab_3 = models.CharField(max_length=400, blank=True,null=True)
    act_rea_trab_3 = models.CharField(max_length=5000, blank=True,null=True)
    enlaces_trab_3 = models.CharField(max_length=5000, blank=True,null=True)
    fecha_registro_reporte = models.DateField(default=datetime.now)

    def __unicode__(self):
        return self.autor

    def get_absolute_url(self):
        return reverse('registro:editar_reporte', kwargs={'pk': self.pk})

registro/forms.py
# -*- coding: utf-8 -*-
from django import forms
from registro.models import Reporte
from django.forms import (
    TextInput, CharField, Select, RadioSelect, Textarea, CheckboxInput, DateTimeField
)
from datetime import *
from django.contrib.admin.widgets import AdminDateWidget
from base.constantes import *

class ReporteForm(forms.ModelForm):
    """
    Formulario con los campos de un Reporte de actividades de un proyecto.
    """
    autor = forms.CharField(label='Autor', widget=TextInput(attrs={
        'class':'form-control input-md',
        'style': 'min-width: 0; width: 100%; display: inline;',
        'required': 'True',
    }), required = True)

    nombre_proyecto = forms.CharField(label='Nombre del Proyecto', widget=TextInput(attrs={
        'class':'form-control input-md',
        'style': 'min-width: 0; width: 100%; display: inline;',
        'required': 'True',
    }), required = True)

    nombre_caravisible = forms.CharField(label='Nombre completo del/la Cara Visible', widget=TextInput(attrs={
        'class':'form-control input-md',
        'style': 'min-width: 0; width: 100%; display: inline;',
        'required': 'True',
    }), required = True)

    nombre_director = forms.ChoiceField(label='Director de Proyecto', widget=Select(attrs={
        'class':'form-control input-md',
        'style': 'min-width: 0; width: 100%; display: inline;',
        'required': 'True',
    }), choices = directores)

    mes = forms.ChoiceField(label='Mes', widget=Select(attrs={
        'class':'form-control input-md',
        'style': 'min-width: 0; width: 100%; display: inline;',
        'required': 'True',
    }), choices = meses)

    ano = forms.ChoiceField(label='Año', widget=Select(attrs={
        'class':'form-control input-md',
        'style': 'min-width: 0; width: 100%; display: inline;',
        'required': 'True',
    }), choices = anos)

    desc_avance = forms.CharField(label='Descripción General del Avance del Proyecto', widget=Textarea(attrs={
        'class':'form-control input-md',
        'style': 'min-width: 0; width: 100%; display: inline;',
        'required': 'True',
    }), required = True)

    obstaculos = forms.CharField(label='Dificultades y Obstáculos', widget=Textarea(attrs={
        'class':'form-control input-md',
        'style': 'min-width: 0; width: 100%; display: inline;',
        'required': 'True',
    }), required = True)

    nombre_trab_1 = forms.CharField(label='Nombre del trabajador', widget=TextInput(attrs={
        'class':'form-control input-md',
        'style': 'min-width: 0; width: 100%; display: inline;',
    }), required = False)

    cargo_trab_1 = forms.ChoiceField(label='Cargo', widget=Select(attrs={
        'class':'form-control input-md',
        'style': 'min-width: 0; width: 100%; display: inline;',
    }), choices = cargos, required = False)

    act_rea_trab_1 = forms.CharField(label='Actividades realizadas', widget=Textarea(attrs={
        'class':'form-control input-md',
        'style': 'min-width: 0; width: 100%; display: inline;',
    }), required = False)

    enlaces_trab_1 = forms.CharField(label='Enlaces de verificación', widget=Textarea(attrs={
        'class':'form-control input-md',
        'style': 'min-width: 0; width: 100%; display: inline;',
    }), required = False)

    nombre_trab_2 = forms.CharField(label='Nombre del trabajador', widget=TextInput(attrs={
        'class':'form-control input-md',
        'style': 'min-width: 0; width: 100%; display: inline;',
    }), required = False)

    cargo_trab_2 = forms.ChoiceField(label='Cargo', widget=Select(attrs={
        'class':'form-control input-md',
        'style': 'min-width: 0; width: 100%; display: inline;',
    }), choices = cargos, required = False)

    act_rea_trab_2 = forms.CharField(label='Actividades realizadas', widget=Textarea(attrs={
        'class':'form-control input-md',
        'style': 'min-width: 0; width: 100%; display: inline;',
    }), required = False)

    enlaces_trab_2 = forms.CharField(label='Enlaces de verificación', widget=Textarea(attrs={
        'class':'form-control input-md',
        'style': 'min-width: 0; width: 100%; display: inline;',
    }), required = False)

    nombre_trab_3 = forms.CharField(label='Nombre del trabajador', widget=TextInput(attrs={
        'class':'form-control input-md',
        'style': 'min-width: 0; width: 100%; display: inline;',
    }), required = False)

    cargo_trab_3 = forms.ChoiceField(label='Cargo', widget=Select(attrs={
        'class':'form-control input-md',
        'style': 'min-width: 0; width: 100%; display: inline;',
    }), choices = cargos, required = False)

    act_rea_trab_3 = forms.CharField(label='Actividades realizadas', widget=Textarea(attrs={
        'class':'form-control input-md',
        'style': 'min-width: 0; width: 100%; display: inline;',
    }), required = False)

    enlaces_trab_3 = forms.CharField(label='Enlaces de verificación', widget=Textarea(attrs={
        'class':'form-control input-md',
        'style': 'min-width: 0; width: 100%; display: inline;',
    }), required = False)

    class Meta:

        model = Reporte
        fields = '__all__'

registro/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponse
from django.views.generic import TemplateView, ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from registro.models import Reporte
from bitacora.models import Bitacora
from forms import ReporteForm
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.views import generic
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, render_to_response, get_object_or_404
from django.views.generic import *
from django.core.urlresolvers import *
from django.db.models import Count
from django.template import RequestContext
from django.contrib.auth.models import User
from django.shortcuts import redirect
from datetime import datetime


class Index(TemplateView):
    """
    Plantilla de inicio del sistema
    """
    template_name = "registro/index.html"

################################
##### Crud de los Reportes #####
################################

class Consultar_reporte(ListView):
    """
    Clase que permite consultar la lista de reportes.
    """
    model = Reporte


class Registrar_reporte(SuccessMessageMixin,CreateView):
    """
    Clase que permite registrar un reporte en el sistema.
    """
    model = Reporte
    form_class = ReporteForm
    success_url = reverse_lazy('registro:consultar_reporte')
    success_message = "Se registro el reporte con éxito"

    def form_valid(self, form):
        """
        Método que permite guardar un evento en la Bitácora cuando
        se registra un Reporte en el sistema.
        """
        usuario = str(self.request.user)
        accion = "Registro un Reporte"
        myDate = datetime.now()
        formatedDate = myDate.strftime("%d-%m-%Y %H:%M")
        fecha_humana = str(formatedDate)
        Bitacora.objects.create(usuario=usuario, accion=accion, fecha=fecha_humana)
        self.object = form.save()
        return super(Registrar_reporte, self).form_valid(form)


class Editar_reporte(SuccessMessageMixin,UpdateView):
    """
    Clase que permite editar la data guardada de un reporte.
    """
    model = Reporte
    form_class = ReporteForm
    success_url = reverse_lazy('registro:consultar_reporte')
    success_message = "Se actualizo el reporte con éxito"

    def get(self, request, *args, **kwargs):
        """
        Método que redirecciona a /index si el usuario
        que intenta editar el reporte no es el autor/creador.
        """
        self.object = self.get_object()
        if str(self.object) == str(self.request.user):
            return super(Editar_reporte, self).get(request, *args, **kwargs)
        else:
            messages_alert = ['No tiene permisos para editar el reporte']
            return render_to_response("registro/index.html",{'messages_alert': messages_alert}, context_instance=RequestContext(request))


class Borrar_reporte(SuccessMessageMixin,DeleteView):
    """
    Clase que permite borrar un reporte registrado en el sistema.
    """
    model = Reporte
    success_url = reverse_lazy('registro:consultar_reporte')
    success_message = "Se elimino el reporte con éxito"

    def get(self, request, *args, **kwargs):
        """
        Método que redirecciona a /index si el usuario
        que intenta borrar el reporte no es el autor/creador.
        """
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        self.object = self.get_object()
        if str(self.object) == str(self.request.user):
            return self.render_to_response(context)
        else:
            messages_alert = ['No tiene permisos para borrar el reporte']
            return render_to_response("registro/index.html",{'messages_alert': messages_alert}, context_instance=RequestContext(request))

    def delete(self, request, *args, **kwargs):
        """
        Función que permite mandar un mensaje al template
        cuando se borra un reporte y registra en la Bitácora que
        se elimino un reporte.
        """
        usuario = str(self.request.user)
        accion = "Elimino un Reporte"
        myDate = datetime.now()
        formatedDate = myDate.strftime("%d-%m-%Y %H:%M")
        fecha_humana = str(formatedDate)
        Bitacora.objects.create(usuario=usuario, accion=accion, fecha=fecha_humana)
        messages.success(self.request, self.success_message)
        return super(Borrar_reporte, self).delete(request, *args, **kwargs)


class Detallar_reporte(DetailView):
    """
    Clase que muestra la lista de entradas de la bitácora
    """
    model = Reporte
    template_name = "registro/reporte_detail.html"

    """
    def get(self, request, *args, **kwargs):
        Método que redirecciona a /index si el usuario
        que intenta ver el reporte no es el autor/creador.
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        if str(self.object) == str(self.request.user):
            return self.render_to_response(context)
        else:
            context = {}
            messages_alert = ['No tiene permisos para ver el reporte']
            return render_to_response("registro/index.html",{'context': context, 'messages_alert': messages_alert}, context_instance=RequestContext(request))
    """

###############################
##### Filtros de búsqueda #####
###############################

class Buscar_reporte(TemplateView):
    """
    Plantilla que tiene el formulario para buscar reportes.
    """
    template_name = "registro/buscar.html"


def busqueda(request):
    """
    Función que recibe los parámetros enviados desde el formulario de
    búsqueda de reportes y filtra los reportes con querysets.
    """
    if 'ano' in request.GET and request.GET['ano'] and 'mes' in request.GET and request.GET['mes']:
        ano = request.GET['ano']
        mes = request.GET['mes']
        reportes_ano = Reporte.objects.filter(ano__icontains=ano)
        reportes = reportes_ano.filter(mes__icontains=mes)
        return render(request, 'registro/busqueda.html',  {'reportes': reportes, 'query': ano,'query2': mes})
    else:
        return HttpResponse('Por favor introduce un termino de búsqueda.')

registro/templates/registro/buscar.html
{% extends "base/base.html" %}
{% block titulo %}Buscar Reportes{% endblock %}
{% block cuerpo %}
<br />
<h1>Buscar Reportes</h1>
<br />

<form action="{% url 'registro:busqueda' %}" method="get">
  <label>Por Año</label>
  <br />
  <select class="form form-control" name="ano" required>
    <option value=""></option>
    <option value="2018">2018</option>
    <option value="2019">2019</option>
  </select>
  <br />
  <label>Por Mes</label>
  <br />
  <select class="form form-control" name="mes" required>
    <option value=""></option>
    <option value="Enero">Enero</option>
    <option value="Febrero">Febrero</option>
    <option value="Marzo">Marzo</option>
    <option value="Abril">Abril</option>
    <option value="Mayo">Mayo</option>
    <option value="Junio">Junio</option>
    <option value="Julio">Julio</option>
    <option value="Agosto">Agosto</option>
    <option value="Septiembre">Septiembre</option>
    <option value="Octubre">Octubre</option>
    <option value="Noviembre">Noviembre</option>
    <option value="Diciembre">Diciembre</option>
  </select>
  <button class="btn btn-success" type="submit">Buscar</button>
</form>
{% endblock %}

registro/templates/registro/busqueda.html
{% extends "base/base.html" %}
{% block titulo %}Resultados de la búsqueda{% endblock %}
{% block cuerpo %}
<br />
<h1>Resultados de la búsqueda</h1>
<br />

{% if reportes %}
  <p>Estas buscado reportes del Año <strong>{{ query }}</strong> en el Mes de <strong>{{ query2}}</strong></p>
  <p>Reportes encontrados: <strong>{{ reportes|length }}</strong>
  <br />
  <br />
  <table border="1px" id="example" class="display" cellspacing="0px" style="width:100%;">
    <thead>
      <tr>
        <th>N</th>
        <th>Nombre del Proyecto</th>
        <th>Nombre del Cara Visible</th>
        <th>Mes</th>
        <th>Año</th>
        <th>Registrado</th>
        <th>Acciones</th>
      </tr>
    </thead>
    <tfoot>
      <tr>
        <th>N</th>
        <th>Nombre del Proyecto</th>
        <th>Nombre del Cara Visible</th>
        <th>Mes</th>
        <th>Año</th>
        <th>Registrado</th>
        <th>Acciones</th>
      </tr>
    </tfoot>
    <tbody>
    {% for x in reportes %}
    <tr>
      <td></td>
      <td>{{ x.nombre_proyecto }}</td>
      <td>{{ x.nombre_caravisible }}</td>
      <td>{{ x.mes }}</td>
      <td>{{ x.ano }}</td>
      <td>{{ x.fecha_registro_reporte }}</td>
      {% if x.autor == user.username %}
        <td>
          <a href="{% url 'registro:editar_reporte' x.id %}"><i class="glyphicon glyphicon-pencil"></i></a>
          &nbsp; | &nbsp;
          <a href="{% url 'registro:detallar_reporte' x.id %}"><i class="glyphicon glyphicon-eye-open"></i></a>
          &nbsp; | &nbsp;
          <a href="{% url 'registro:borrar_reporte' x.id %}"><i class="glyphicon glyphicon-trash"></i></a>
        </td>
      {% else %}
        <td>
          <a href="{% url 'registro:detallar_reporte' x.id %}"><i class="glyphicon glyphicon-eye-open"></i></a>
        </td>
      {% endif %}
    </tr>
    {% endfor %}
    </tbody>
  </table>
{% else %}
  <p>Ningún reporte coincide con el criterio de búsqueda.</p>
  <br />
  <a href="{% url 'registro:buscar' %}"><button type="button" class="btn btn-primary">Buscar de nuevo</button></a>
{% endif %}
{% endblock %}

registro/templates/registro/index.html
{% extends "base/base.html" %}
{% block titulo %}Inicio{% endblock %}
{% block cuerpo %}
{% load staticfiles %}
<div align="center">
  <br />
  <h1>Bienvenido</h1>
</div>
{% endblock %}

registro/templates/registro/reporte_confirm_delete.html
{% extends "base/base.html" %}
{% block titulo %}Borrar Reporte{% endblock %}
{% block cuerpo %}
<br />
<form method="post">{% csrf_token %}
  <h4>
    ¿Estás seguro que quieres eliminar el reporte de: <b>{{ object.nombre_proyecto }} de {{ object.mes }} del {{ object.ano }}</b>?
  </h4>
  <br />
  <br />
  <a href="/consultar_reporte"><button type="button" class="btn btn-primary">Volver</button></a>
  <button class="btn btn-danger" type="submit">Borrar</button>
</form>
{% endblock %}

registro/templates/registro/reporte_form.html
{% extends "base/base.html" %}
{% block titulo %}Registrar Reporte{% endblock %}
{% block cuerpo %}
<br />
<h1>Registrar Reporte</h1>
<br />

<form method="post">{% csrf_token %}
   
  <input id="id_autor" name="autor" required="True" type="text" value="{{ user.username }}" />

  {{ form.fecha_registro_reporte }}

  <div class="">
    <b>{{ form.nombre_proyecto.label }}</b>
    <br />
    {{ form.nombre_proyecto }}
    {% if form.nombre_proyecto.errors %}
      <p>{{ form.nombre_proyecto.errors}}</p>
    {% endif %}
  </div>

  <div class="row">
    <div class="col-sm-6">
      <div class="">
        <b>{{ form.nombre_caravisible.label }}</b>
        <br />
        {{ form.nombre_caravisible }}
        {% if form.nombre_caravisible.errors %}
          <p>{{ form.nombre_caravisible.errors}}</p>
        {% endif %}
      </div>
    </div>
    <div class="col-sm-6">
      <div class="">
        <b>{{ form.nombre_director.label }}</b>
        <br />
        {{ form.nombre_director }}
        {% if form.nombre_director.errors %}
          <p>{{ form.nombre_director.errors}}</p>
        {% endif %}
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-6">
      <div class="">
        <b>{{ form.mes.label }}</b>
        <br />
        {{ form.mes }}
        {% if form.mes.errors %}
          <p>{{ form.mes.errors}}</p>
        {% endif %}
      </div>
    </div>
    <div class="col-sm-6">
      <div class="">
        <b>{{ form.ano.label }}</b>
        <br />
        {{ form.ano }}
        {% if form.ano.errors %}
          <p>{{ form.ano.errors}}</p>
        {% endif %}
      </div>
    </div>
  </div>

  <div class="">
    <b>{{ form.desc_avance.label }}</b>
    <br />
    {{ form.desc_avance }}
    {% if form.desc_avance.errors %}
      <p>{{ form.desc_avance.errors}}</p>
    {% endif %}
  </div>

  <div class="">
    <b>{{ form.obstaculos.label }}</b>
    <br />
    {{ form.obstaculos }}
    {% if form.obstaculos.errors %}
      <p>{{ form.obstaculos.errors}}</p>
    {% endif %}
  </div>

<br />

<h3>Integrantes del equipo</h3>

  <table class="tabla_trabajadores" border="1px" style="width:100%">
    <thead>
      <tr>
        <th><b>N</b></th>
        <th><b>Nombre del trabajador</b></th>
        <th><b>Cargo</b></th>
        <th><b>Actividades realizadas</b></th>
        <th><b>Enlaces de verificación</b></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>1</td>
        <td>
          {{ form.nombre_trab_1 }}
          {% if form.nombre_trab_1.errors %}
            <p>{{ form.nombre_trab_1.errors}}</p>
          {% endif %}
        </td>
        <td>
          {{ form.cargo_trab_1 }}
          {% if form.cargo_trab_1.errors %}
            <p>{{ form.cargo_trab_1.errors}}</p>
          {% endif %}
        </td>
        <td>
          {{ form.act_rea_trab_1 }}
          {% if form.act_rea_trab_1.errors %}
            <p>{{ form.act_rea_trab_1.errors}}</p>
          {% endif %}
        </td>
        <td>
          {{ form.enlaces_trab_1 }}
          {% if form.enlaces_trab_1.errors %}
            <p>{{ form.enlaces_trab_1.errors}}</p>
          {% endif %}
        </td>
      </tr>
      <tr>
        <td>2</td>
        <td>
          {{ form.nombre_trab_2 }}
          {% if form.nombre_trab_2.errors %}
            <p>{{ form.nombre_trab_2.errors}}</p>
          {% endif %}
        </td>
        <td>
          {{ form.cargo_trab_2 }}
          {% if form.cargo_trab_2.errors %}
            <p>{{ form.cargo_trab_2.errors}}</p>
          {% endif %}
        </td>
        <td>
          {{ form.act_rea_trab_2 }}
          {% if form.act_rea_trab_2.errors %}
            <p>{{ form.act_rea_trab_2.errors}}</p>
          {% endif %}
        </td>
        <td>
          {{ form.enlaces_trab_2 }}
          {% if form.enlaces_trab_2.errors %}
            <p>{{ form.enlaces_trab_2.errors}}</p>
          {% endif %}
        </td>
      </tr>
      <tr>
        <td>3</td>
        <td>
          {{ form.nombre_trab_3 }}
          {% if form.nombre_trab_3.errors %}
            <p>{{ form.nombre_trab_3.errors}}</p>
          {% endif %}
        </td>
        <td>
          {{ form.cargo_trab_3 }}
          {% if form.cargo_trab_3.errors %}
            <p>{{ form.cargo_trab_3.errors}}</p>
          {% endif %}
        </td>
        <td>
          {{ form.act_rea_trab_3 }}
          {% if form.act_rea_trab_3.errors %}
            <p>{{ form.act_rea_trab_3.errors}}</p>
          {% endif %}
        </td>
        <td>
          {{ form.enlaces_trab_3 }}
          {% if form.enlaces_trab_3.errors %}
            <p>{{ form.enlaces_trab_3.errors}}</p>
          {% endif %}
        </td>
      </tr>
    </tbody>
  </table>
  <br />
  <a href="{% url 'registro:index' %}"><button type="button" class="btn btn-primary">Volver</button></a>
  <button class="btn btn-info" type="reset">Limpiar</button>
  <button class="btn btn-success" type="submit">Registrar</button>
</form>
{% endblock %}

registro/templates/registro/reporte_list.html
{% extends "base/base.html" %}
{% block titulo %}Lista de Reportes{% endblock %}
{% block cuerpo %}
<br />
<h1>Lista de Reportes</h1>
<br />

{% include 'registro/tabla.html' %}
{% endblock %}

registro/templates/registro/tabla.html
<table border="1px" id="example" class="display" cellspacing="0px" style="width:100%;">
  <thead>
    <tr>
      <th>N</th>
      <th>Nombre del Proyecto</th>
      <th>Nombre del Cara Visible</th>
      <th>Mes</th>
      <th>Año</th>
      <th>Registrado</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tfoot>
    <tr>
      <th>N</th>
      <th>Nombre del Proyecto</th>
      <th>Nombre del Cara Visible</th>
      <th>Mes</th>
      <th>Año</th>
      <th>Registrado</th>
      <th>Acciones</th>
    </tr>
  </tfoot>
  <tbody>
  {% for x in object_list %}
  <tr>
    <td></td>
    <td>{{ x.nombre_proyecto }}</td>
    <td>{{ x.nombre_caravisible }}</td>
    <td>{{ x.mes }}</td>
    <td>{{ x.ano }}</td>
    <td>{{ x.fecha_registro_reporte }}</td>
    {% if x.autor == user.username %}
      <td>
        <a href="{% url 'registro:editar_reporte' x.id %}"><i class="glyphicon glyphicon-pencil"></i></a>
        &nbsp; | &nbsp;
        <a href="{% url 'registro:detallar_reporte' x.id %}"><i class="glyphicon glyphicon-eye-open"></i></a>
        &nbsp; | &nbsp;
        <a href="{% url 'registro:borrar_reporte' x.id %}"><i class="glyphicon glyphicon-trash"></i></a>
      </td>
    {% else %}
      <td>
        <a href="{% url 'registro:detallar_reporte' x.id %}"><i class="glyphicon glyphicon-eye-open"></i></a>
      </td>
    {% endif %}
  </tr>
  {% endfor %}
  </tbody>
</table>